server:
  port: 8082

spring:
  application:
    name: second-service

eureka:
  instance:
    appname: second-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka