server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
          - Path=/employee/**
        filters:
          - StripPrefix=1
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
          - Path=/consumer/**
        filters:
          - StripPrefix=1

eureka:
  instance:
    appname: gateway-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka